version: "3.5"

services:
  all:
    build:
      context: ../
      dockerfile: ./.buildkite/Dockerfile
    environment:
      - "GO111MODULE=on"
      - BUILDKITE_BRANCH
      - FOSSA_API_KEY
    volumes:
      - ..:/samples-go

